version: "3.6"

services:
  parity-plunger:
    image: makerdao/testchain-pymaker:unit-testing
    container_name: parity-plunger-test
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    user: root
    working_dir: /home/parity

  plunger-list:
    image: plunger
    command: --rpc-host $ETH_RPC_URL --source parity_txqueue --list $ETH_FROM
    environment:
      - ETH_RPC_URL
      - ETH_FROM

  plunger-force:
    image: plunger
    command: |
      --rpc-host $ETH_RPC_URL --source parity_txqueue --override-with-zero-txs \
      --eth-key=key_file=/keystore/keystore.json \
      --gas-price $GAS_PRICE $ETH_FROM
    environment:
      - ETH_RPC_URL
      - ETH_FROM
    volumes:
      - ${KEYSTORE_DIR}:/keystore